######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 13 09:42:40 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bmp.h CameraDriver.h CWindow.h yuv2bmp.h
SOURCES += bmp.c CameraDriver.c CWindow.cc main.cc yuv2bmp.c
